### ISSUE TITLE
Testing in Windows

### ISSUE THREAD

**Issue by lunzueta** [takiyu/DeepPose#3]
Hi @takiyu, I'm testing your program in Windows 10, with Anaconda. I've already been able to run correctly in this platform other programs that use Chainer (like https://github.com/mitmul/deeppose and https://github.com/mitmul/chainer-faster-rcnn). In this case, I'm getting the following error:
`[2016/07/10 20:32:21] INFO (7680) __parents_main__ : GPU mode (0) (stage: 0, joint_idx: -1, resume: False)`
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`File "C:\Anaconda2\lib\multiprocessing\forking.py", line 381, in main`
`self = load(from_parent)`
`File "C:\Anaconda2\lib\pickle.py", line 1384, in load`
`return Unpickler(file).load()`
`File "C:\Anaconda2\lib\pickle.py", line 864, in load`
`dispatch[key](self)`
`File "C:\Anaconda2\lib\pickle.py", line 1096, in load_global`
`klass = self.find_class(module, name)`
`File "C:\Anaconda2\lib\pickle.py", line 1132, in find_class`
`klass = getattr(mod, name)`
`AttributeError: 'module' object has no attribute 'first_conv_func'`
I've tried to debug this to see if I could get a solution for this, but I haven't been able (I'm not so experienced in Python, and this seems to be quite advanced). Any clue?

**Comment by takiyu** [comment]
Thanks for your bug report.
I think Windows `multiprocessing` package is the cause.
The package serializes function arguments with `pickle`, but only top level functions can be serialized.

I fixed it, but I do not have any Windows PC.
Please use `test_windows` branch and report it.

**Comment by lunzueta** [comment]
Thanks for the update @takiyu. I switched to the new branch and tested it, but I'm still getting the same error :-(

**Comment by takiyu** [comment]
I setup a new Windows7 PC and test my program.
As a result, I found that Windows multiprocessing implementation is far different from Linux.

I created new settings variable `ASYNC_MODE` and please use `thread` mode on Windows.
Only 2 processes (`main` and `image_servers`) will be created.

**Comment by lunzueta** [comment]
Thanks @takiyu. It's training now :-)
However, I can't visualize anything in http://localhost:8889/ even though that's the server port I have defined in the json file. What might be happening?

**Comment by takiyu** [comment]
Can you see a black bar on the top of the webpage?
Visualizing process is the last step of training pipeline, so you can not see any images while first batch is training.

If some batches ware trained and no images could be seen, please edit line28 in `src/train.py` as following and tell me the log.

```
# imgviewer.logger.setLevel(INFO)
imgviewer.logger.setLevel(DEBUG)
```

**Comment by lunzueta** [comment]
I get the error "Unable to connect", so I can't see any webpage. I'm using Firefox.

**Comment by takiyu** [comment]
Is there any error log?
Have you installed `Flask` and `flask-socketio`?

**Comment by lunzueta** [comment]
I have Flask 0.10.1 and Flask-SocketIO 0.6.0 installed.

Well, at some point I can see an error in the log, but it seems to ignore it and it continues training normally:

`[2016/07/11 22:03:33] INFO (17092) __parents_main__ : GPU mode (0) (stage: 0, joint_idx: -1, resume: True)`
`Process Process-1:`
`Traceback (most recent call last):`
`File "C:\Anaconda2\lib\multiprocessing\process.py", line 258, in _bootstrap`
`self.run()`
`File "C:\Anaconda2\lib\multiprocessing\process.py", line 114, in run`
`self._target(*self._args, **self._kwargs)`
`File "C:\LUI\Procrast\Software\deeppose_takiyu\scripts\image_servers\imgviewer\app.py", line 167, in new_server`
`logger=False, engineio_logger=False)`
`TypeError: __init__() got an unexpected keyword argument 'async_mode'`

**Comment by takiyu** [comment]
Maybe Flask-SocketIO is too old. The latest version is 2.5.

**Comment by lunzueta** [comment]
Yes! I updated that and it worked! Thank you very much and congratulations for your great work. It is very useful for the community!
